words = [
    "apple", "banana", "cherry", "date", "elderberry", "fig", "grape", 
    "honeydew", "kiwi", "lemon", "mango", "nectarine", "orange", 
    "papaya", "quince", "raspberry", "strawberry", "tangerine", 
    "ugli", "vanilla", "watermelon", "xigua", "yellow", "zucchini", 
    "antelope", "buffalo", "cheetah", "dolphin", "elephant", "flamingo", 
    "gorilla", "hippopotamus", "iguana", "jaguar", "kangaroo", "llama", 
    "mongoose", "narwhal", "octopus", "penguin", "quokka", "rhinoceros", 
    "squid", "tiger", "umbrellabird", "vulture", "walrus", "xerus", 
    "yak", "zebra", "avocado", "broccoli", "carrot", "daikon", 
    "eggplant", "fennel", "garlic", "horseradish", "iceberg", 
    "jalapeno", "kale", "lettuce", "mushroom", "nutmeg", "oregano", 
    "parsley", "quinoa", "radish", "spinach", "tomato", "udon", 
    "vinegar", "wasabi", "xanthan", "yeast", "zest", "algorithm", 
    "binary", "cache", "database", "encryption", "firewall", "gateway", 
    "hardware", "internet", "java", "kernel", "logic", "middleware", 
    "network", "object", "protocol", "query", "router", "syntax", 
    "token", "upload", "variable", "web", "xml", "yield", "z-index", 
    "abstract", "boolean", "class", "debug", "exception", "function", 
    "global", "heap", "inheritance", "json", "key", "loop", 
    "module", "namespace", "operator", "parameter", "queue", 
    "recursion", "stack", "tuple", "unicode", "version", "while", 
    "x-coordinate", "yield", "zero"
]